# Generated by Django 3.2.4 on 2021-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20210602_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='frequency',
            field=models.DecimalField(decimal_places=2, default=94.9, max_digits=5),
            preserve_default=False,
        ),
    ]
