# Generated by Django 3.2.4 on 2021-06-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_station_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ManyToManyField(to='songs.Song', verbose_name='list of songs to be played that particular day')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.station', verbose_name='Station that the daily schedule is tied to')),
            ],
        ),
        migrations.CreateModel(
            name='DailyScheduleSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('daily_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.dailyschedule', verbose_name='Corresponding Daily Schedule')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.song', verbose_name='Song to be played at specific time')),
            ],
        ),
    ]
